services:
    whoami:
        scaler:
            up: "cmd"
            down: "cmd"
    whoami2:
        scaler:
            up: "cmd up"
            down: "cmd down"
probes:
    mock-cpu: "basic-cpu"
    mock-ram: "basic-ram"
    mock-response-time: "random-timer"

rules:
    cpulimit: "cpu > .25"
